# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-21 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('IP_id', models.AutoField(primary_key=True, serialize=False)),
                ('vlan', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20, null=True)),
                ('thing', models.CharField(max_length=40, null=True)),
                ('domain', models.CharField(max_length=20, null=True)),
                ('person_name', models.CharField(max_length=10, null=True)),
                ('person_tel', models.CharField(max_length=15, null=True)),
                ('admin_name', models.CharField(max_length=10, null=True)),
                ('admin_tel', models.CharField(max_length=15, null=True)),
                ('bbs_admin_name', models.CharField(max_length=10, null=True)),
                ('bbs_admin_tel', models.CharField(max_length=15, null=True)),
                ('blj_user', models.CharField(max_length=10, null=True)),
                ('blj_password', models.CharField(max_length=20, null=True)),
                ('system_type', models.CharField(max_length=10, null=True)),
                ('cpu', models.CharField(max_length=10, null=True)),
                ('momory', models.CharField(max_length=10, null=True)),
                ('storage', models.CharField(max_length=10, null=True)),
                ('assistance', models.CharField(max_length=20, null=True)),
                ('ssh', models.CharField(max_length=20, null=True)),
                ('telnet', models.CharField(max_length=15, null=True)),
                ('host_user', models.CharField(max_length=20, null=True)),
                ('host_password', models.CharField(max_length=20, null=True)),
                ('host_manage_type', models.CharField(max_length=10, null=True)),
                ('sql_type', models.CharField(max_length=10, null=True)),
                ('is_post', models.CharField(max_length=10, null=True)),
                ('post', models.CharField(max_length=10, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('colony', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_number', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_type', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
