# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-22 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='admin_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='admin_tel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='assistance',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='bbs_admin_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='bbs_admin_tel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='blj_password',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='blj_user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='colony',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='cpu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='domain',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='host',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ip',
            name='host_manage_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='host_password',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='host_user',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='is_post',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='momory',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='person_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='person_tel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='post',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='remark',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='sql_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ssh',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='storage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='system_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='telnet',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='thing',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='vlan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
