# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0004_ip_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('times', models.IntegerField(null=True)),
                ('list1', models.CharField(max_length=500, null=True)),
                ('list0', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
