# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-22 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0005_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='list0',
            field=models.CharField(max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='list1',
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
