# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0006_auto_20180722_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='times',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
