# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-01 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0008_ip_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='ms',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
