# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-04 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0010_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_mail',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
