# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-04 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0011_user_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_mail',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
