# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0012_auto_20180804_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
