# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 08:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0014_auto_20180808_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='count0',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='time',
            name='count1',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 16, 10, 42, 94606)),
        ),
    ]
