# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0015_auto_20180808_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(default=datetime.datetime(2018, 8, 8, 17, 9, 8, 673606), max_length=50),
        ),
    ]
